from pathlib import Path
from datetime import datetime, timezone
from SentinelAI.models.transaction import Transaction
from SentinelAI.models.verdict import Verdict
from SentinelAI.logs.audit_logger import audit_logger

class EmailDispatcher:
    EMAILS_DIR = Path("SentinelAI/emails")

    @classmethod
    async def dispatch_client_notice(cls, tx: Transaction, verdict: Verdict) -> str:
        cls.EMAILS_DIR.mkdir(parents=True, exist_ok=True)
        
        email_id = f"EMAIL_{tx.trace_id}.html"
        file_path = cls.EMAILS_DIR / email_id

        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Important Security Notice regarding your SentinelAI Account</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #0f172a; color: #f8fafc; padding: 40px; }}
        .card {{ background-color: #1e293b; border-radius: 12px; padding: 32px; max-width: 600px; margin: 0 auto; border: 1px solid #334155; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }}
        .header {{ border-bottom: 2px solid #ef4444; padding-bottom: 16px; margin-bottom: 24px; }}
        .header h2 {{ color: #ef4444; margin: 0; font-size: 24px; }}
        .detail-row {{ display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #334155; }}
        .label {{ color: #94a3b8; }}
        .value {{ font-weight: bold; color: #f8fafc; }}
        .footer {{ margin-top: 32px; font-size: 13px; color: #64748b; text-align: center; }}
        .btn {{ display: inline-block; background-color: #3b82f6; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: bold; margin-top: 24px; }}
    </style>
</head>
<body>
    <div class="card">
        <div class="header">
            <h2>SentinelAI Security Notice</h2>
        </div>
        <p>Dear Valued Client (Account ID: <strong>{tx.user_id}</strong>),</p>
        <p>Our automated AI compliance monitoring system detected a transaction requiring your immediate verification or protective hold.</p>
        
        <div class="detail-row"><span class="label">Transaction Trace ID:</span><span class="value">{tx.trace_id}</span></div>
        <div class="detail-row"><span class="label">Timestamp (UTC):</span><span class="value">{tx.timestamp.strftime('%Y-%m-%d %H:%M:%S')}</span></div>
        <div class="detail-row"><span class="label">Amount Attempted:</span><span class="value">${tx.amount:,.2f} {tx.currency}</span></div>
        <div class="detail-row"><span class="label">Merchant:</span><span class="value">{tx.merchant}</span></div>
        <div class="detail-row"><span class="label">Location:</span><span class="value">{tx.device.city}, {tx.device.country_code}</span></div>
        <div class="detail-row"><span class="label">Security Status:</span><span class="value" style="color: #ef4444;">{verdict.recommended_action.value}</span></div>

        <p style="margin-top: 20px; color: #cbd5e1;">If you initiated this transfer, please confirm using your mobile authenticator app. If you did not authorize this transaction, your account security freeze remains active.</p>
        
        <div style="text-align: center;">
            <a href="#" class="btn">Verify Transaction in App</a>
        </div>

        <div class="footer">
            Generated by SentinelAI End-to-End Compliance Pipeline &bull; Reference: {tx.trace_id}
        </div>
    </div>
</body>
</html>"""

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        await audit_logger.log_event(
            trace_id=tx.trace_id,
            action="DISPATCHED_CLIENT_EMAIL",
            actor="Automation_EmailDispatcher",
            payload={"recipient": tx.user_id, "file_path": str(file_path)}
        )
        return str(file_path)
