from pathlib import Path
from datetime import datetime, timezone
from SentinelAI.models.transaction import Transaction
from SentinelAI.models.verdict import PandasAnalysisResult, Verdict
from SentinelAI.logs.audit_logger import audit_logger

class ReportGenerator:
    REPORTS_DIR = Path("SentinelAI/reports")

    @classmethod
    async def generate_investigation_report(cls, tx: Transaction, pandas_res: PandasAnalysisResult, verdict: Verdict) -> str:
        cls.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        report_path = cls.REPORTS_DIR / f"REPORT_{tx.trace_id}.md"

        content = f"""# Compliance Investigation Report — SentinelAI

**Report Timestamp:** {datetime.now(timezone.utc).isoformat()}  
**Case Trace ID:** `{tx.trace_id}`  
**Subject Account ID:** `{tx.user_id}`  

---

## 1. Executive Summary & Verdict
* **Risk Level:** **{verdict.risk_level.value}**
* **Confidence Score:** `{verdict.confidence_score * 100:.1f}%`
* **Identified Typology:** `{verdict.fraud_typology.value}`
* **Recommended Action:** **{verdict.recommended_action.value}**
* **AI Engine:** `{verdict.model_used}`

### Analytical Reasoning
> {verdict.reasoning}

---

## 2. Transaction Profile
| Field | Data |
| :--- | :--- |
| **Transaction ID** | `{tx.transaction_id}` |
| **Amount** | `${tx.amount:,.2f} {tx.currency}` |
| **Merchant** | `{tx.merchant}` ({tx.merchant_category}) |
| **Masked PAN** | `{tx.card_pan_masked}` |
| **Device IP** | `{tx.device.ip_address}` |
| **Location** | `{tx.device.city}, {tx.device.country_code}` |

---

## 3. Statistical Deterministic Metrics (Pandas Engine)
* **Z-Score Outlier Rating:** `{pandas_res.z_score}`
* **1-Hour Rolling Velocity:** `{pandas_res.velocity_1h_count}` transactions
* **24-Hour Cumulative Spend:** `${pandas_res.velocity_24h_spend:,.2f}`
* **Geo-Velocity Distance:** `{pandas_res.geo_distance_km} KM`
* **Triggered Rule Signatures:**
{chr(10).join([f'  - `{rule}`' for rule in pandas_res.triggered_rules]) if pandas_res.triggered_rules else '  - *No specific static threshold rules triggered.*'}

---

## 4. Regulatory Audit Compliance Note
This document was automatically generated by the SentinelAI compliance automation pipeline. All transactional snapshots and AI decision rationales are permanently chained in the immutable cryptographic WORM audit trail under trace reference `{tx.trace_id}`.
"""
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(content)

        await audit_logger.log_event(
            trace_id=tx.trace_id,
            action="GENERATED_INVESTIGATION_REPORT",
            actor="Automation_ReportGenerator",
            payload={"file_path": str(report_path)}
        )
        return str(report_path)
