import hashlib
from typing import Dict, Any
from SentinelAI.models.transaction import Transaction
from SentinelAI.models.verdict import PandasAnalysisResult

class PromptBuilder:
    @staticmethod
    def anonymize_user_id(user_id: str) -> str:
        # Pseudo-anonymize user identifier
        return f"CLIENT_{hashlib.md5(user_id.encode()).hexdigest()[:6].upper()}"

    @classmethod
    def build_prompt(cls, tx: Transaction, pandas_res: PandasAnalysisResult) -> Dict[str, str]:
        anon_id = cls.anonymize_user_id(tx.user_id)
        
        system_prompt = (
            "You are SentinelAI, an elite Senior Compliance & Financial Crime AI analyst working in a Tier-1 Fintech bank. "
            "Your task is to review deterministic flags generated by the Pandas statistical engine and render an authoritative, "
            "legally sound AML / Fraud verdict in strict JSON output format matching the requested Pydantic schema.\n\n"
            "Respond ONLY with valid JSON containing keys: risk_level, confidence_score, fraud_typology, reasoning, recommended_action."
        )

        user_content = f"""
TRANSACTION PROFILE (ANONYMIZED FOR PII PROTECTION):
- Trace ID: {tx.trace_id}
- Anonymized Entity ID: {anon_id}
- Amount: {tx.amount:.2f} {tx.currency}
- Timestamp (UTC): {tx.timestamp.isoformat()}
- Merchant: {tx.merchant} (Category: {tx.merchant_category})
- Masked Card PAN: {tx.card_pan_masked}
- Device Country/City: {tx.device.country_code} / {tx.device.city}
- IP Address: {tx.device.ip_address[:8]}...[REDACTED]

PANDAS DETERMINISTIC STATISTICAL ANALYSIS:
- Is Suspicious Flag: {pandas_res.is_suspicious}
- Triggered Rules: {', '.join(pandas_res.triggered_rules) if pandas_res.triggered_rules else 'None'}
- Statistical Z-Score: {pandas_res.z_score}
- 1-Hour Velocity Count: {pandas_res.velocity_1h_count}
- 24-Hour Total Spend: ${pandas_res.velocity_24h_spend:,.2f}
- Estimated Geo Velocity Distance: {pandas_res.geo_distance_km} KM
- Summary: {pandas_res.summary}

INSTRUCTIONS:
Determine the exact Risk Level (LOW, MEDIUM, HIGH, CRITICAL), Fraud Typology, Confidence Score (0.00 to 1.00), detailed legal/analytical reasoning, and recommended action (PASS, MONITOR, BLOCK, ESCALATE_TO_HUMAN).
"""
        return {
            "system_prompt": system_prompt,
            "user_prompt": user_content
        }
