"""
SentinelAI Core Pydantic v2 Schemas Module.

Contains all unified domain models for transaction stream processing, automated
statistical fraud cases, LLM compliance reasoning, ticketing, notifications,
and executive reporting. Designed with strict typing and Pydantic v2 validation.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Literal
from pydantic import BaseModel, ConfigDict, Field, field_validator


class Transaction(BaseModel):
    """Represents an ingested financial transaction stream log entry."""

    model_config = ConfigDict(
        populate_by_name=True,
        str_strip_whitespace=True,
        json_schema_extra={
            "example": {
                "transaction_id": "tx_a1b2c3d4",
                "account_id": "ACC_10012",
                "amount": 12500.0,
                "currency": "USD",
                "timestamp": "2026-07-01T15:30:00Z",
                "ip_address": "198.51.100.14",
                "country": "US",
                "device_id": "DEV_99123A",
                "transaction_type": "transfer",
                "merchant_category": "crypto",
                "status": "completed",
            }
        },
    )

    transaction_id: str = Field(..., description="Unique transaction identifier")
    account_id: str = Field(..., description="Account or user identifier")
    amount: float = Field(..., ge=0.0, description="Transaction amount")
    currency: str = Field(..., min_length=3, max_length=4, description="ISO currency code")
    timestamp: datetime = Field(..., description="UTC timestamp of the transaction")
    ip_address: str = Field(..., description="Origin IPv4/IPv6 address")
    country: str = Field(..., min_length=2, max_length=3, description="Country code (ISO 3166-1 alpha-2)")
    device_id: str = Field(..., description="Device fingerprint or hardware ID")
    transaction_type: str = Field(..., description="Type of transaction (deposit, withdrawal, transfer)")
    merchant_category: str = Field(..., description="Merchant category code or descriptor")
    status: str = Field(..., description="Execution status (completed, pending, failed)")

    @field_validator("currency")
    @classmethod
    def validate_currency_upper(cls, v: str) -> str:
        return v.upper()


class FraudCase(BaseModel):
    """Represents a suspicious incident flagged by the deterministic statistical engine."""

    model_config = ConfigDict(populate_by_name=True)

    case_id: str = Field(..., description="Unique case investigation identifier")
    rule_triggered: str = Field(..., description="Name or code of the AML rule triggered")
    risk_score: float = Field(..., ge=0.0, le=100.0, description="Calculated statistical risk score")
    related_accounts: List[str] = Field(default_factory=list, description="List of linked account IDs")
    related_transactions: List[str] = Field(default_factory=list, description="List of linked transaction IDs")
    timestamps: List[datetime] = Field(default_factory=list, description="Chronological event timestamps")
    evidence_summary: str = Field(..., description="Human/machine readable statistical summary")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Case creation time")


class InvestigationReport(BaseModel):
    """Structured intermediate report synthesizing multi-hop transaction findings."""

    model_config = ConfigDict(populate_by_name=True)

    case_id: str = Field(..., description="Linked fraud case ID")
    findings: List[str] = Field(default_factory=list, description="List of factual investigative findings")
    suspicious_indicators: List[str] = Field(default_factory=list, description="Specific AML indicators observed")
    cross_references: List[str] = Field(default_factory=list, description="Links to external registries or watchlists")
    summary: str = Field(..., description="Synthesized narrative of the investigation")
    processing_time_ms: int = Field(..., ge=0, description="Time taken to assemble report in milliseconds")


class LLMVerdict(BaseModel):
    """Structured cognitive output generated by Groq AI / LLM compliance evaluation."""

    model_config = ConfigDict(populate_by_name=True)

    case_id: str = Field(..., description="Linked fraud case ID")
    risk_level: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        ..., description="Final assigned compliance risk category"
    )
    action: Literal["MONITOR", "REQUEST_KYC", "FREEZE", "ESCALATE"] = Field(
        ..., description="Recommended enforcement action"
    )
    confidence: float = Field(..., ge=0.0, le=1.0, description="AI confidence score (0.00 to 1.00)")
    reasoning: str = Field(..., description="Detailed analytical and legal rationale")
    regulatory_basis: str = Field(..., description="Applicable regulation (e.g. PSD2, AMLD5, FATF Rec 16)")
    recommended_deadline_days: int = Field(..., ge=0, description="SLA for completing action in days")
    processing_time_ms: int = Field(..., ge=0, description="LLM inference latency in milliseconds")
    model_used: str = Field(..., description="Name of the generative model (e.g. llama3-70b-8192)")
    tokens_used: int = Field(..., ge=0, description="Total API tokens consumed")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Verdict generation time")


class ComplianceTicket(BaseModel):
    """Formal compliance ticket generated for tracking by L2/L3 compliance officers."""

    model_config = ConfigDict(populate_by_name=True)

    ticket_id: str = Field(..., description="Unique issue ticket ID (e.g. TKT-8812A)")
    case_id: str = Field(..., description="Linked fraud case ID")
    title: str = Field(..., description="Concise issue headline")
    priority: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(..., description="Operational ticket priority")
    description: str = Field(..., description="Full problem specification")
    evidence_summary: str = Field(..., description="Synthesized evidence attached to ticket")
    action_required: str = Field(..., description="Concrete task required from compliance analyst")
    sla_hours: int = Field(..., ge=1, description="Resolution SLA in hours")
    tags: List[str] = Field(default_factory=list, description="Categorical workflow tags")
    assignee: str = Field(..., description="Assigned queue or officer ID")
    status: str = Field(default="OPEN", description="Current ticket workflow status")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Ticket creation time")


class ClientEmail(BaseModel):
    """Automated customer notification email generated following compliance evaluation."""

    model_config = ConfigDict(populate_by_name=True)

    email_id: str = Field(..., description="Unique email dispatch ID")
    case_id: str = Field(..., description="Linked fraud case ID")
    client_name: str = Field(..., description="Addressee full name or entity name")
    account_id: str = Field(..., description="Recipient account identifier")
    subject: str = Field(..., description="Email subject line")
    body: str = Field(..., description="HTML or plaintext message body")
    tone: str = Field(default="formal_and_protective", description="Communication tone used")
    language: str = Field(default="en", min_length=2, max_length=10, description="ISO language code")
    documents_requested: List[str] = Field(default_factory=list, description="List of required KYC/SOF documents")
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Generation timestamp")


class SessionReport(BaseModel):
    """Aggregated executive summary report for a batch processing window or audit session."""

    model_config = ConfigDict(populate_by_name=True)

    report_id: str = Field(..., description="Unique session report ID")
    date: str = Field(..., description="Date string or reporting window label (e.g. 2026-07-01)")
    total_transactions: int = Field(..., ge=0, description="Total transactions ingested")
    total_cases: int = Field(..., ge=0, description="Total fraud cases flagged")
    risk_distribution: Dict[str, Any] = Field(
        default_factory=dict, description="Counts/percentages across risk tiers"
    )
    actions_breakdown: Dict[str, Any] = Field(
        default_factory=dict, description="Breakdown of recommended enforcement actions"
    )
    tickets_generated: int = Field(..., ge=0, description="Total compliance tickets created")
    emails_generated: int = Field(..., ge=0, description="Total customer notices generated")
    tokens_used: int = Field(..., ge=0, description="Total LLM tokens consumed in session")
    estimated_cost_usd: float = Field(..., ge=0.0, description="Estimated API compute cost in USD")
    executive_summary: str = Field(..., description="Macro-level narrative summary for leadership")
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Report generation time")
